const actionTypes = {
  GET_APP_READY: 'GET_APP_READY',
  INIT_APP: 'INIT_APP',
  IS_FETCHING_BOOKS: 'IS_FETCHING_BOOKS',

  SET_ACTIVE_BOOK: 'SET_ACTIVE_BOOK',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  SHOW_LOADING: 'SHOW_LOADING',
  HIDE_LOADING: 'HIDE_LOADING',

  SET_BOOKS: 'SET_BOOKS',

  ADD_LESSON: 'ADD_LESSON',
  REMOVE_LESSON: 'REMOVE_LESSON',
  EDIT_LESSON: 'EDIT_LESSON',

  ADD_VOCAB: 'ADD_VOCAB',
  REMOVE_VOCAB: 'REMOVE_VOCAB',
  EDIT_VOCAB: 'EDIT_VOCAB',
};

export default actionTypes;
