const actionTypes = {
  GET_APP_READY: 'GET_APP_READY',
  INIT_APP: 'INIT_APP',
  IS_FETCHING_BOOKS: 'IS_FETCHING_BOOKS',
  IS_FETCHING_LESSONS: 'IS_FETCHING_LESSONS',
  IS_FETCHING_VOCABS: 'IS_FETCHING_VOCABS',

  SET_ACTIVE_BOOK: 'SET_ACTIVE_BOOK',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  SHOW_LOADING: 'SHOW_LOADING',
  HIDE_LOADING: 'HIDE_LOADING',

  SET_BOOKS: 'SET_BOOKS',

  SET_LESSONS: 'SET_LESSONS',

  SET_VOCABS: 'SET_VOCABS',
};

export default actionTypes;
