const Languages = {};

Languages.en = {
  ADD: 'Add',
  ADD_BOOK: 'Add book',
  ADD_LESSON: 'Add lesson',
  ADD_VOCAB: 'Add Vocabulary',
  BACK: 'Back',
  BOOK_TITLE: 'Title',
  BOOK_TITLE_PLACE_HOLDER: 'Mina no nihongo',
  BOOKS: 'Books',
  CANCEL: 'Cancel',
  DESELECT_ALL: 'Deselect all',
  DICTATION: 'Dictation',
  DICTATION_REMIND_MSG: 'Please select the lessons to start',
  DICTIONARY: 'Dictionary',
  DONE: 'Done',
  DOWNLOADING_BOOK: 'Downloading the book...',
  EDIT: 'Edit',
  EDIT_BOOK: 'Edit book',
  EDIT_LESSON: 'Edit lesson',
  EDIT_VOCAB: 'Edit vocab',
  FREE_BOOKS_MSG: 'Free Book from server',
  GOOGLE_IMAGES: 'Google images',
  IMPORT: 'Import',
  IMPORT_BOOK: 'Import Book',
  IMPORTED: ' imported.',
  IMPORTING: 'Importing...',
  INPUT_YOUR_ANSWER_HERE: 'Input your answer here.',
  LANGUAGE: 'Language',
  LESSON_TITLE: 'Title',
  LESSON_TITLE_PLACEHOLDER: 'e.g. Lesson 1',
  LESSONS: 'Lessons',
  LOADING: 'Loading...',
  LOG_OUT: 'Log out',
  NO_ACTIVE_BOOK_MSG: 'Please select a book to continue.',
  NO_BOOK_MSG: 'You do not have any book yet.',
  NO_DATA_IN_DICTATION: 'Please add vocabs before starting training.',
  NO_LESSON_MSG: 'You do not have any lesson yet.',
  NO_RESULTS_MSG: 'Start training to get results.',
  NO_VOCABS_MSG: 'You do not have any vacabulary yet.',
  OPTIONAL: 'Optional',
  OUT_OF_DICT: 'Out of dictation',
  PLEASE_SELECT: 'Please select',
  PRONUNCIATION: 'Pronunciation',
  QUESTIONS: 'Questions',
  RESULTS: 'Results',
  SAVE: 'Save',
  SCORE: 'Score',
  SELECT_ALL: 'Select all',
  SETTINGS: 'Settings',
  SHARE_THIS_VOCAB: 'Share this vocabulary',
  START: 'Start',
  STOP: 'Stop',
  TAGS: 'Tags',
  TRAINING_TYPE: 'Training type',
  TRANSLATE_FROM: 'Translate from',
  TRANSLATION: 'Translation',
  UNIT_LESSONS: ' lessons',
  UNIT_VOCABS: ' vocabs',
  USE_FOR_SPEECH: 'Use for speech',
  VERSION: 'Version',
  VOCABULARY: 'Vocabulary',
  WAIT_A_MOMENT: 'Please wait for a moment.',
  YOUR_ANSWERS: 'Your answers',
};

Languages.en.VOCAB_TYPE_SHORT_FORM = {
  adj: 'adj',
  adv: 'adv',
  all: 'all',
  n: 'n',
  other: 'other',
  pn: 'pn',
  v: 'v',
};

Languages.en.VOCAB_TYPE = {
  adj: 'Adjective',
  adv: 'Adverb',
  all: 'All',
  n: 'Noun',
  other: 'Other',
  pn: 'Pronoun',
  v: 'Verb',
};

Languages.zh = {
  ...Languages.en,
  ADD: '新增',
  ADD_BOOK: '新增單詞本',
  ADD_LESSON: '新增課文',
  ADD_VOCAB: '新增單詞',
  BACK: '返回',
  BOOK_TITLE: '單詞本名稱',
  BOOK_TITLE_PLACE_HOLDER: 'e.g. 大家的日本語初級I',
  BOOKS: '單詞本',
  CANCEL: '取消',
  DESELECT_ALL: '全不選',
  DICTATION: '默書',
  DICTATION_REMIND_MSG: '請選擇要進行練習的課文。',
  DICTIONARY: '字典',
  DONE: '完成',
  DOWNLOADING_BOOK: '正在下載單詞本...',
  EDIT: '編輯',
  EDIT_BOOK: '編輯單詞本',
  EDIT_LESSON: '編輯課文',
  EDIT_VOCAB: '編輯單詞',
  FREE_BOOKS_MSG: '以下單詞本供免費下載',
  GOOGLE_IMAGES: 'Google 圖片',
  IMPORT: '開始導入',
  IMPORT_BOOK: '導入單詞本',
  IMPORTED: ' 已成功導入。',
  IMPORTING: '導入中...',
  INPUT_YOUR_ANSWER_HERE: '輸入你聽見的單詞',
  LANGUAGE: '語言',
  LESSON_TITLE: '標題',
  LESSON_TITLE_PLACEHOLDER: 'e.g. 第一課',
  LESSONS: '課文',
  LOADING: '載入中...',
  LOG_OUT: '登出',
  NO_ACTIVE_BOOK_MSG: '請先選擇要練習的單詞本。',
  NO_BOOK_MSG: '你還未有任何單詞本。',
  NO_DATA_IN_DICTATION: '要先增加單詞才能進行練習。',
  NO_LESSON_MSG: '你還未有任何課文。',
  NO_RESULTS_MSG: '你現再還未有練習的成績。',
  NO_VOCABS_MSG: '你還未有任何單詞在這單詞本。',
  OPTIONAL: '可選',
  OUT_OF_DICT: '不在練習中出現',
  PLEASE_SELECT: '請選擇',
  PRONUNCIATION: '讀音',
  QUESTIONS: '問題',
  RESULTS: '成績',
  SAVE: '保存',
  SCORE: '分數',
  SELECT_ALL: '全選',
  SETTINGS: '設定',
  SHARE_THIS_VOCAB: '分享',
  START: '開始',
  STOP: '停止',
  TAGS: '標籤',
  TRAINING_TYPE: '練習類別',
  TRANSLATE_FROM: '翻譯由',
  TRANSLATION: '翻譯',
  UNIT_LESSONS: '個課文',
  UNIT_VOCABS: '個單詞',
  USE_FOR_SPEECH: '使用發音',
  VERSION: '版本',
  VOCABULARY: '單詞',
  WAIT_A_MOMENT: '請稍等...',
  YOUR_ANSWERS: '你的答案',
};

Languages.zh.VOCAB_TYPE_SHORT_FORM = {
  adj: '形',
  adv: '副',
  all: '全部',
  n: '名',
  other: '其他',
  pn: '代',
  v: '動',
};

Languages.zh.VOCAB_TYPE = {
  adj: '形容詞',
  adv: '副詞',
  all: '全部',
  n: '名詞',
  other: '其他',
  pn: '代名詞',
  v: '動詞',
};

Languages.ja = {
  ...Languages.en,
};

export default Languages;
